name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # This can be your default branch or any other branch
  pull_request:
    branches:
      - main  # Adjust as per your needs
  workflow_dispatch:  # Allows manual triggering

permissions:
  pull-requests: read  # Allows SonarCloud to decorate PRs with analysis results

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest  # Use 'windows-latest' if you need a Windows runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Install Java 17 explicitly
      - name: Install OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version
          
      # Set JAVA_HOME to Java 17
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      # Set up .NET (if using .NET)
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Adjust to the .NET version you're using (e.g., '6.x', '7.x')

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Run SonarCloud Scan with explicit Java version
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: |
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}  
            -Dsonar.sources=.   
            -X
        env:
          DOTNET_ROOT: /usr/share/dotnet
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  # Set Java 17 explicitly

      # Run unit tests (optional, but recommended)
      - name: Run unit tests
        run: dotnet test --configuration Release --no-build

      # Publish SonarCloud results
      - name: Publish SonarCloud results
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: |
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}  # Replace with your SonarCloud project key
            -Dsonar.organization=${{ secrets.SONAR_ORG }}  # Replace with your SonarCloud organization name
            -Dsonar.sources=.  # Path to your source files (default is the root directory)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
